/**
 * dsh-research-autoresearch browser half — GENERATED by scripts/build-client.mjs
 * from src/client/*; do not edit by hand. Envelope shape mirrors the installed
 * dsh-github-manager precedent: virtual CommonJS modules resolved by a local
 * __require, host externals delegated to the loader's require.
 */
window.__ModuleLoader__.load({
	id: 'dsh-research-autoresearch',
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
		const __modules = {
			'locales.ts': function (require, module, exports) {
				"use strict";
				Object.defineProperty(exports, "__esModule", { value: true });
				exports.en = exports.zh = void 0;
				exports.zh = {
				    title: '科研可视化总控台',
				    description: 'AutoResearch 五张进度卡的持久开关。开＝强制注入；关＝跟随各工具部署配置。会话内的临时开合请用 research_ui_switch 工具。',
				    master: '总闸：全部强制开',
				    literature: '📚 文献检索卡 (arxiv_search)',
				    scoring: '📊 LQS 评分卡 (lit_score)',
				    panel: '🧪 研究进度面板 (research_state)',
				    guardian: '🧭 停滞检测卡 (stall_check)',
				    review: '⭐ 评审记分卡 (peer_review)',
				    overridden: '持久覆盖',
				    save: '保存',
				    discard: '放弃修改',
				    unsaved: '未保存',
				    saving: '保存中…',
				    readOnly: '当前文档为只读，无法保存。',
				    saveFailed: '上次保存未被接受，请修正后重试。',
				};
				exports.en = {
				    title: 'Research Visualization Control',
				    description: 'Durable switches for the five AutoResearch progress cards. On forces the cards; off follows each tool\u2019s deployment config. For per-session flips use the research_ui_switch tool.',
				    master: 'Master: force all on',
				    literature: '📚 Literature recall cards (arxiv_search)',
				    scoring: '📊 LQS scoreboard (lit_score)',
				    panel: '🧪 Research progress panel (research_state)',
				    guardian: '🧭 Stall traffic-light (stall_check)',
				    review: '⭐ Review scoreboard (peer_review)',
				    overridden: 'durable override',
				    save: 'Save',
				    discard: 'Discard',
				    unsaved: 'unsaved',
				    saving: 'saving…',
				    readOnly: 'The current document is read-only.',
				    saveFailed: 'The last save was refused; fix and retry.',
				};
			},
			'card-model.ts': function (require, module, exports) {
				"use strict";
				Object.defineProperty(exports, "__esModule", { value: true });
				exports.ResearchUiCardController = exports.FIELDS = exports.RESEARCH_UI_NS = void 0;
				/**
				 * The research-ui card model: a React-free controller that stages drafts
				 * over the paired 'research-ui' settings section and writes them on save.
				 * Reads resolve through the settings layers (user over composition over the
				 * schema default); a field present in the raw user layer marks overridden.
				 */
				const client_1 = require("@deepseek-ai/dsh-client-runtime/client");
				/** The paired host settings namespace, spelled exactly as the host brands it. */
				exports.RESEARCH_UI_NS = 'research-ui';
				/** Every durable field the card exposes, in display order. */
				exports.FIELDS = ['defaultCards', 'literatureCards', 'scoringCards', 'panelCards', 'guardianCards', 'reviewCards'];
				class ResearchUiCardController {
				    /** @param scope - the bound settings scope for the research-ui namespace. */
				    constructor(scope) {
				        this.scope = scope;
				        this.staged = new Map();
				        this.saving = false;
				        this.failed = false;
				        this.store = (0, client_1.createSnapshotStore)(this.project());
				        scope.subscribe(() => this.publish());
				    }
				    /** Build the face the card's slot registration injects. */
				    inject() {
				        return {
				            hooks: { researchUi: this.store },
				            toggle: (field, value) => this.stage(field, value),
				            save: () => this.save(),
				            discard: () => {
				                if (this.staged.size === 0 && !this.failed)
				                    return;
				                this.staged.clear();
				                this.failed = false;
				                this.publish();
				            },
				        };
				    }
				    stage(field, value) {
				        this.staged.set(field, Boolean(value));
				        this.failed = false;
				        this.publish();
				    }
				    /** Write every staged draft through the scope, in staging order. */
				    async save() {
				        if (this.saving || this.staged.size === 0)
				            return;
				        this.saving = true;
				        this.failed = false;
				        this.publish();
				        const writes = [];
				        for (const [field, value] of this.staged)
				            writes.push(this.scope.set(field, value));
				        try {
				            await Promise.all(writes);
				            this.staged.clear();
				        }
				        catch {
				            // Keep the drafts: a save that did not land must not throw away what
				            // the user toggled; the next edit or save retries from the same state.
				            this.failed = true;
				        }
				        finally {
				            this.saving = false;
				            this.publish();
				        }
				    }
				    user() {
				        return this.scope.getSnapshot().user ?? {};
				    }
				    switchState(field) {
				        if (this.staged.has(field)) {
				            return { value: this.staged.get(field), overridden: true };
				        }
				        const resolved = (this.scope.getSnapshot().value ?? {});
				        return { value: Boolean(resolved[field]), overridden: Object.hasOwn(this.user(), field) };
				    }
				    /** The full face snapshot: layers resolved, drafts previewed, flags fresh. */
				    project() {
				        const snapshot = this.scope.getSnapshot();
				        const switches = {};
				        for (const f of exports.FIELDS)
				            switches[f] = this.switchState(f);
				        return {
				            available: true,
				            writable: snapshot.writable !== false,
				            dirty: this.staged.size > 0,
				            saving: this.saving,
				            failed: this.failed,
				            switches,
				        };
				    }
				    publish() {
				        this.store.set(this.project());
				    }
				}
				exports.ResearchUiCardController = ResearchUiCardController;
			},
			'ResearchUiCard.tsx': function (require, module, exports) {
				"use strict";
				Object.defineProperty(exports, "__esModule", { value: true });
				exports.ResearchUiCard = ResearchUiCard;
				const jsx_runtime_1 = require("react/jsx-runtime");
				/**
				 * The research-ui card face: a collapsed header (title + unsaved badge) that
				 * expands to six durable switches and a save/discard footer. Plain React
				 * with the host's design tokens — CSS modules are build-pipeline territory
				 * this dependency-free bundle deliberately stays out of.
				 */
				const react_1 = require("react");
				// Styles mirror the official card sheet, built from host design tokens.
				const cardStyle = { listStyle: 'none', border: '1px solid var(--dsw-alias-border-l2)', borderRadius: '12px', background: 'var(--dsw-alias-bg-layer-3)', transition: 'border-color .16s, background .16s' };
				const cardOpenStyle = { ...cardStyle, background: 'var(--dsw-alias-bg-layer-2)', borderColor: 'var(--dsw-alias-label-dimmed)' };
				const headerStyle = { width: '100%', appearance: 'none', border: '0', background: 'none', font: 'inherit', color: 'inherit', textAlign: 'left', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '12px', padding: '14px 16px', borderRadius: '12px' };
				const headTextStyle = { flex: '1', minWidth: '0', display: 'flex', flexDirection: 'column', gap: '4px' };
				const nameStyle = { fontSize: '15px', fontWeight: 600, lineHeight: '1.4', color: 'var(--dsw-alias-label-primary)' };
				const descStyle = { fontSize: '13px', lineHeight: '1.5', color: 'var(--dsw-alias-label-tertiary)' };
				const pendingStyle = { flex: 'none', borderRadius: '999px', padding: '1px 8px', fontSize: '11px', lineHeight: '17px', background: 'var(--dsw-alias-bg-layer-4)', color: 'var(--dsw-alias-label-secondary)' };
				const chevronStyle = { flex: 'none', transform: 'none', transition: 'transform .15s', fontSize: '12px' };
				const bodyStyle = { padding: '2px 16px 14px', display: 'flex', flexDirection: 'column', gap: '2px' };
				const rowStyle = { display: 'flex', alignItems: 'center', gap: '10px', padding: '8px 0', borderTop: '1px solid var(--dsw-alias-border-l1)', cursor: 'pointer' };
				const rowLabelStyle = { flex: '1', minWidth: '0', fontSize: '13px', color: 'var(--dsw-alias-label-primary)' };
				const badgeStyle = { marginLeft: '8px', fontSize: '10px', color: 'var(--dsw-alias-label-tertiary)', border: '1px solid var(--dsw-alias-border-l1)', borderRadius: '4px', padding: '0 4px' };
				const footerStyle = { display: 'flex', justifyContent: 'flex-end', alignItems: 'center', gap: '8px', paddingTop: '10px' };
				const btnStyle = { appearance: 'none', border: '1px solid var(--dsw-alias-border-l2)', borderRadius: '8px', background: 'var(--dsw-alias-bg-layer-3)', color: 'inherit', font: 'inherit', fontSize: '13px', padding: '4px 12px', cursor: 'pointer' };
				const btnPrimaryStyle = { ...btnStyle, background: 'var(--dsw-alias-accent, #4f6ef7)', color: '#fff', border: '0' };
				const failStyle = { flex: '1', fontSize: '12px', color: '#e5484d' };
				/** Each switch row: the settings field written and the locale key rendered. */
				const ROWS = [
				    ['defaultCards', 'master'],
				    ['literatureCards', 'literature'],
				    ['scoringCards', 'scoring'],
				    ['panelCards', 'panel'],
				    ['guardianCards', 'guardian'],
				    ['reviewCards', 'review'],
				];
				function ResearchUiCard(props) {
				    const s = props.useResearchUi((snapshot) => snapshot);
				    const [open, setOpen] = (0, react_1.useState)(false);
				    if (!s || !s.available)
				        return null;
				    const { t } = props;
				    const disabled = !s.writable || s.saving;
				    return ((0, jsx_runtime_1.jsxs)("li", { style: open ? cardOpenStyle : cardStyle, children: [(0, jsx_runtime_1.jsxs)("button", { type: "button", style: headerStyle, "aria-expanded": open, onClick: () => setOpen(!open), children: [(0, jsx_runtime_1.jsxs)("span", { style: headTextStyle, children: [(0, jsx_runtime_1.jsx)("span", { style: nameStyle, children: t('title') }), (0, jsx_runtime_1.jsx)("span", { style: descStyle, children: t('description') })] }), s.dirty ? (0, jsx_runtime_1.jsx)("span", { style: pendingStyle, children: t('unsaved') }) : null, (0, jsx_runtime_1.jsx)("span", { "aria-hidden": true, style: open ? { ...chevronStyle, transform: 'rotate(90deg)' } : chevronStyle, children: "\u25B8" })] }), open ? ((0, jsx_runtime_1.jsxs)("div", { style: bodyStyle, children: [ROWS.map(([field, label]) => ((0, jsx_runtime_1.jsxs)("label", { style: rowStyle, children: [(0, jsx_runtime_1.jsxs)("span", { style: rowLabelStyle, children: [t(label), s.switches[field].overridden ? (0, jsx_runtime_1.jsx)("span", { style: badgeStyle, children: t('overridden') }) : null] }), (0, jsx_runtime_1.jsx)("input", { type: "checkbox", checked: s.switches[field].value, disabled: disabled, onChange: (e) => props.toggle(field, e.target.checked) })] }, field))), s.dirty || s.saving || s.failed ? ((0, jsx_runtime_1.jsxs)("div", { style: footerStyle, children: [(0, jsx_runtime_1.jsx)("span", { style: failStyle, children: s.failed ? t('saveFailed') : ' ' }), (0, jsx_runtime_1.jsx)("button", { type: "button", style: btnStyle, disabled: s.saving, onClick: () => props.discard(), children: t('discard') }), (0, jsx_runtime_1.jsx)("button", { type: "button", style: btnPrimaryStyle, disabled: disabled || !s.dirty, onClick: () => props.save(), children: s.saving ? t('saving') : t('save') })] })) : null, !s.writable ? (0, jsx_runtime_1.jsx)("div", { style: descStyle, children: t('readOnly') }) : null] })) : null] }));
				}
			},
			'index.ts': function (require, module, exports) {
				"use strict";
				Object.defineProperty(exports, "__esModule", { value: true });
				exports.inject = exports.LOCALE_NS = void 0;
				exports.apply = apply;
				/**
				 * Browser half entry, discovered through package.json dsh.client and run by
				 * the host's client plugin loader. Registers the card dictionaries, binds a
				 * controller to the paired settings section, and injects the card into the
				 * plugins tab. The node half owns every behavior; this half only edits the
				 * durable layer of the researchUi switch, which the host syncs live.
				 */
				const locales_ts_1 = require("./locales.ts");
				const card_model_ts_1 = require("./card-model.ts");
				const ResearchUiCard_tsx_1 = require("./ResearchUiCard.tsx");
				/** The locale namespace the card renders through. */
				exports.LOCALE_NS = 'dsh-research-autoresearch';
				/**
				 * Services this half touches through ctx. The browser mounts client plugins
				 * with ctx.plugin({ inject, apply }) on a real cordis context: reading any
				 * other service (ctx.locale, ctx.slots, ctx.settingsScope) without it listed
				 * here throws "cannot get property ... without inject" and the card dies.
				 */
				exports.inject = ['locale', 'settingsScope', 'slots'];
				function apply(ctx) {
				    ctx.effect(() => ctx.locale.register(exports.LOCALE_NS, { zh: locales_ts_1.zh, en: locales_ts_1.en }), 'dsh-research-autoresearch: card dictionaries');
				    const card = new card_model_ts_1.ResearchUiCardController(ctx.settingsScope.bind({ namespace: card_model_ts_1.RESEARCH_UI_NS }));
				    ctx.slots.inject('settings.plugin.item', () => ctx.slots.register({
				        name: 'settings.plugin.item',
				        key: card_model_ts_1.RESEARCH_UI_NS,
				        locale: exports.LOCALE_NS,
				        inject: () => card.inject(),
				    }, ResearchUiCard_tsx_1.ResearchUiCard));
				}
			},
		};
		const __cache = {};
		const __require = (spec) => {
			if (typeof spec === 'string' && spec.slice(0, 2) === './') {
				const id = spec.slice(2);
				const define = __modules[id];
				if (define === undefined) throw new Error('dsh-research-autoresearch client: unknown module ' + id);
				if (!(id in __cache)) {
					const inner = { exports: {} };
					__cache[id] = inner.exports;
					define(__require, inner, inner.exports);
					__cache[id] = inner.exports;
				}
				return __cache[id];
			}
			return require(spec);
		};
		const entry = __require("./index.ts");
		Object.assign(exports, entry);
		return module.exports;
	},
});
