/**
 * Compiles the browser half (src/client/*.ts|*.tsx) into lib/client.js: the
 * window.__ModuleLoader__ envelope the host discovers via package.json
 * dsh.client. In-repo cards get this shape from the tsdown preset; an
 * out-of-repo package must reproduce the same output format, so this script
 * is that reproduction — ts.transpileModule per module (CommonJS + react-jsx),
 * wrapped verbatim in the loader contract the installed precedent uses.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import vm from 'node:vm'
import ts from 'typescript'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(root, 'src', 'client')
const MODULES = ['locales.ts', 'card-model.ts', 'ResearchUiCard.tsx', 'index.ts']
const ENTRY = './index.ts'
/** Host externals: everything else the emitted code requires must be relative. */
const EXTERNALS = new Set(['react', 'react/jsx-runtime', '@deepseek-ai/dsh-client-runtime/client'])

const compiled = MODULES.map((file) => {
  const code = readFileSync(join(SRC, file), 'utf8')
  const out = ts.transpileModule(code, {
    fileName: file,
    compilerOptions: {
      target: ts.ScriptTarget.ES2020,
      module: ts.ModuleKind.CommonJS,
      jsx: ts.JsxEmit.ReactJSX,
      removeComments: false,
    },
  })
  if ((out.diagnostics ?? []).length > 0) {
    throw new Error(file + ': ' + out.diagnostics.map((d) => ts.flattenDiagnosticMessageText(d.messageText, ' ')).join('; '))
  }
  return { file, text: out.outputText.trimEnd() }
})

// Import-graph discipline: declared externals only, relative specs resolve.
for (const { file, text } of compiled) {
  for (const m of text.matchAll(/require\((['"])([^'"]+)\1\)/g)) {
    const spec = m[2]
    if (!spec.startsWith('./')) {
      if (!EXTERNALS.has(spec)) throw new Error(file + ': undeclared browser external ' + spec)
    } else if (!MODULES.includes(spec.slice(2))) {
      throw new Error(file + ': unresolvable client module ' + spec)
    }
  }
}

const indent = (text, pad) => text.split('\n').map((l) => (l.trim() ? pad + l : l)).join('\n')
// Single-quoted keys and one-deeper bodies, matching the installed precedent byte-style.
const moduleDefs = compiled
  .map(({ file, text }) => "\t\t\t'" + file + "': function (require, module, exports) {\n" + indent(text, '\t\t\t\t') + '\n\t\t\t},')
  .join('\n')

const envelope = `/**
 * dsh-research-autoresearch browser half — GENERATED by scripts/build-client.mjs
 * from src/client/*; do not edit by hand. Envelope shape mirrors the installed
 * dsh-github-manager precedent: virtual CommonJS modules resolved by a local
 * __require, host externals delegated to the loader's require.
 */
window.__ModuleLoader__.load({
\tid: 'dsh-research-autoresearch',
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
\t\tconst __modules = {
${moduleDefs}
\t\t};
\t\tconst __cache = {};
\t\tconst __require = (spec) => {
\t\t\tif (typeof spec === 'string' && spec.slice(0, 2) === './') {
\t\t\t\tconst id = spec.slice(2);
\t\t\t\tconst define = __modules[id];
\t\t\t\tif (define === undefined) throw new Error('dsh-research-autoresearch client: unknown module ' + id);
\t\t\t\tif (!(id in __cache)) {
\t\t\t\t\tconst inner = { exports: {} };
\t\t\t\t\t__cache[id] = inner.exports;
\t\t\t\t\tdefine(__require, inner, inner.exports);
\t\t\t\t\t__cache[id] = inner.exports;
\t\t\t\t}
\t\t\t\treturn __cache[id];
\t\t\t}
\t\t\treturn require(spec);
\t\t};
\t\tconst entry = __require(${JSON.stringify(ENTRY)});
\t\tObject.assign(exports, entry);
\t\treturn module.exports;
\t},
});
`

new vm.Script(envelope) // parse gate: the emitted text must be valid script code
writeFileSync(join(root, 'lib', 'client.js'), envelope)
console.log('built lib/client.js  (' + envelope.length + ' chars, ' + MODULES.length + ' modules)')
